### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-python-exercise1-ShakirAhmed-Python#1]
Hi Shakir, 

Great work on the assignment. 
Some relatively minor feedback: I would like to see authorship (first name, last name) on all notebooks. This help collaborators know who to contact with any issues from the code or notebook in general. 

I would also prefer that you use the template repositories that I created. Some may contain an autograder, so this would not be present in repositories you create from scratch. 

I'm giving you full credit, contingent on you adding authorship by September 15th. 
-Greg

**Comment by Shakir0585** [comment]
Hi Greg,

Updated the authorship details in all files. In case of cloning of repo, i will make sure to clone all repos made by you as a template for future projects.

**Comment by Shakir0585** [comment]
closed by mistake. will leave the closure status to you

**Comment by Gchism94** [comment]
This looks good. Next time, you can close the issue, I will reopen if there are other issues. 
For future submissions, please also keep the .README file. These are essential in Github.
